#!/bin/bash
#SBATCH -J BehavClon
#SBATCH --ntasks=1
#SBATCH --partition=t4v1,p100
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH -c 2 # Number of cpus requested
#SBATCH --output ../OUTPUTS/behavCloning_ml4h-%j-%a.out
#SBATCH --export=ALL
#SBATCH --mem=8GB
#SBATCH --array=1-108%20

echo $(tail -n+$SLURM_ARRAY_TASK_ID BC_exp_params.txt | head -n1)

cd ../scripts

python -u train_behavCloning.py $(tail -n+$SLURM_ARRAY_TASK_ID ../slurm_scripts/BC_exp_params.txt | head -n1)